-- CleanTapi Shop: mandatory Telegram verification and private manager threads.
-- Run this file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.telegram_verifications (
  id uuid primary key default gen_random_uuid(),
  flow_token text not null unique,
  browser_secret_hash text not null,
  language text not null default 'ua' check (language in ('ua', 'ru')),
  telegram_user_id bigint,
  telegram_chat_id bigint,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  telegram_phone text,
  verified_at timestamptz,
  used_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists telegram_verifications_user_idx
  on public.telegram_verifications (telegram_user_id, created_at desc);
create index if not exists telegram_verifications_expiry_idx
  on public.telegram_verifications (expires_at);

create table if not exists public.shop_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  verification_id uuid not null unique references public.telegram_verifications(id) on delete restrict,
  telegram_user_id bigint not null,
  telegram_chat_id bigint not null,
  telegram_username text,
  telegram_phone text not null,
  forum_topic_id bigint unique,
  customer_name text not null,
  status text not null default 'new' check (status in ('new', 'working', 'completed')),
  order_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists shop_orders_telegram_user_idx
  on public.shop_orders (telegram_user_id, created_at desc);
create index if not exists shop_orders_topic_idx
  on public.shop_orders (forum_topic_id);
create index if not exists shop_orders_status_idx
  on public.shop_orders (status, created_at desc);

alter table public.telegram_verifications enable row level security;
alter table public.shop_orders enable row level security;

-- Deliberately create no public RLS policies. These tables contain customer data
-- and are accessed only by server-side Netlify functions with the service role.

revoke all on table public.telegram_verifications from anon, authenticated;
revoke all on table public.shop_orders from anon, authenticated;
revoke all on sequence public.shop_orders_order_number_seq from anon, authenticated;

comment on table public.telegram_verifications is
  'Short-lived Telegram ownership checks for CleanTapi Shop checkout.';
comment on table public.shop_orders is
  'Verified shop orders and their Telegram manager forum-topic mapping.';

select
  to_regclass('public.telegram_verifications') is not null as telegram_verifications_ready,
  to_regclass('public.shop_orders') is not null as shop_orders_ready;
